const fs = require('fs');

const TRANSLATIONS = {
  en: {
    // Referral
    referral_slip: 'Referral Slip',
    generated: 'Generated',
    generating_slip: 'Generating referral slip...',
    emergency_slip: 'Emergency Referral Slip',
    date: 'Date',
    ref: 'Ref',
    patient_details_label: 'PATIENT DETAILS',
    name: 'Name',
    age_gestation: 'Age / Gestation',
    village: 'Village',
    clinical_findings: 'CLINICAL FINDINGS',
    ai_risk_level: 'AI Risk Level',
    ai_confidence: 'AI Confidence',
    referral_details: 'REFERRAL DETAILS',
    referred_from: 'Referred From',
    referred_to: 'Referred To',
    urgency: 'Urgency',
    reason: 'Reason',
    emergency_priority: '⚠ EMERGENCY REFERRAL — Please prioritize this patient',
    referring_clinician: 'REFERRING CLINICIAN',
    facility: 'Facility',
    contact: 'Contact',
    signature: 'Signature',
    stamp: 'Stamp',
    footer_note: 'Generated by MaaAI · AI-powered maternal health system · ABDM compliant',
    download_pdf: 'Download PDF',
    share: 'Share',
    shared: 'Shared!',

    // Audit
    all_events: 'All events',
    immutable: 'Immutable',
    ai_decision: 'AI Decision',
    anm_action: 'ANM Action',
    mo_review: 'MO Review',

    // Scan
    document_scan: 'Document Scan',
    online: 'Online',
    position_doc: 'Position document inside frame',
    ocr_unavailable: 'OCR unavailable offline',
    connect_internet: 'Connect to internet to scan documents',
    supported_docs: 'Supported documents:',
    available_online: 'Available when online',
    enter_manual: 'Enter data manually instead',
    data_extracted: 'Data extracted successfully',
    extracted_info: 'Extracted Information',
    review_correct: 'Review and correct if needed',
    edit: 'Edit',
    confirm_save: 'Confirm & Save',
    edit_extracted: 'Edit Extracted Data',
    save_patient_record: 'Save to Patient Record',
  },
  hi: {
    // Referral
    referral_slip: 'रेफरल पर्ची',
    generated: 'जनरेट किया गया',
    generating_slip: 'रेफरल पर्ची जनरेट की जा रही है...',
    emergency_slip: 'आपातकालीन रेफरल पर्ची',
    date: 'दिनांक',
    ref: 'संदर्भ',
    patient_details_label: 'रोगी का विवरण',
    name: 'नाम',
    age_gestation: 'आयु / गर्भावस्था (सप्ताह)',
    village: 'गाँव',
    clinical_findings: 'नैदानिक निष्कर्ष',
    ai_risk_level: 'एआई जोखिम स्तर',
    ai_confidence: 'एआई सत्यता',
    referral_details: 'रेफरल विवरण',
    referred_from: 'कहाँ से रेफर किया गया',
    referred_to: 'कहाँ रेफर किया गया',
    urgency: 'तात्कालिकता',
    reason: 'कारण',
    emergency_priority: '⚠ आपातकालीन रेफरल — कृपया इस रोगी को प्राथमिकता दें',
    referring_clinician: 'रेफर करने वाले चिकित्सक',
    facility: 'सुविधा',
    contact: 'संपर्क करें',
    signature: 'हस्ताक्षर',
    stamp: 'मुहर',
    footer_note: 'माँ-एआई (MaaAI) द्वारा जनरेट किया गया · एआई-संचालित मातृ स्वास्थ्य प्रणाली',
    download_pdf: 'पीडीएफ (PDF) डाउनलोड करें',
    share: 'शेयर करें',
    shared: 'शेयर किया गया!',

    // Audit
    all_events: 'सभी घटनाएं',
    immutable: 'अपरिवर्तनीय',
    ai_decision: 'एआई निर्णय',
    anm_action: 'एएनएम कार्रवाई',
    mo_review: 'एमओ समीक्षा',

    // Scan
    document_scan: 'दस्तावेज़ स्कैन',
    online: 'ऑनलाइन',
    position_doc: 'दस्तावेज़ को फ्रेम के अंदर रखें',
    ocr_unavailable: 'ऑफ़लाइन ओसीआर अनुपलब्ध',
    connect_internet: 'दस्तावेज़ स्कैन करने के लिए इंटरनेट से कनेक्ट करें',
    supported_docs: 'समर्थित दस्तावेज़:',
    available_online: 'ऑनलाइन होने पर उपलब्ध',
    enter_manual: 'इसके बजाय मैन्युअल रूप से डेटा दर्ज करें',
    data_extracted: 'डेटा सफलतापूर्वक निकाला गया',
    extracted_info: 'निकाली गई जानकारी',
    review_correct: 'समीक्षा करें और आवश्यकतानुसार सुधारें',
    edit: 'संपादित करें',
    confirm_save: 'पुष्टि करें और सहेजें',
    edit_extracted: 'निकाला गया डेटा संपादित करें',
    save_patient_record: 'रोगी के रिकॉर्ड में सहेजें',
  }
};

const filepath = 'c:/Users/zaree/Documents/MaAi/constants/translations.ts';
let code = fs.readFileSync(filepath, 'utf8');

// Insert EN
const enKeys = Object.entries(TRANSLATIONS.en).map(([k, v]) => `    ${k}: '${v}',`).join('\\n');
code = code.replace(/(rec_text:\\s*'.*',)/, `$1\n\n${enKeys}`);

// Insert HI
const hiKeys = Object.entries(TRANSLATIONS.hi).map(([k, v]) => `    ${k}: '${v}',`).join('\\n');
code = code.replace(/(rec_text:\\s*'.*',)([^}]*)$/, `$1$2\n\n${hiKeys}`);

fs.writeFileSync(filepath, code);
console.log("Translations added!");
